### ISSUE TITLE
output of cap2tt is missing xml:lang attribute

### ISSUE THREAD

**Issue by shinjantiwary** [skynav/cap2tt#4]
I am using the following command to generate the xmls using cap2tt module:
-d --warn-on all --force-encoding Shift_JIS --output-indent --output-directory <outDir> <input.cap>

ttpe seems to run into error processing this Xml with the following errors:

[E]:{file:/home/stiwary/Projects/Shimada/GitHub/test/convertedXml/sample-001-gen.xml}:[2,132]:XSD(cvc-complex-type.4): Attribute 'lang' must appear on element 'tt'.
[E]:{file:/home/stiwary/Projects/Shimada/GitHub/test/convertedXml/sample-001-gen.xml}:[4,31]:XSD(cvc-complex-type.2.4.a): Invalid content was found starting with element 'ttm:item'. One of '{"http://www.w3.org/ns/ttml#metadata":agent, "http://www.w3.org/ns/ttml#metadata":copyright, "http://www.w3.org/ns/ttml#metadata":desc, "http://www.w3.org/ns/ttml#metadata":title, "http://www.w3.org/ns/ttml":metadata, "http://www.w3.org/ns/ttml#parameter":profile, "http://www.w3.org/ns/ttml":styling, "http://www.w3.org/ns/ttml":layout}' is expected.
[E]:{file:/home/stiwary/Projects/Shimada/GitHub/test/convertedXml/sample-001-gen.xml}:[7,30]:XSD(cvc-complex-type.2.4.a): Invalid content was found starting with element 'initial'. One of '{"http://www.w3.org/ns/ttml#metadata":agent, "http://www.w3.org/ns/ttml#metadata":copyright, "http://www.w3.org/ns/ttml#metadata":desc, "http://www.w3.org/ns/ttml#metadata":title, "http://www.w3.org/ns/ttml":metadata, "http://www.w3.org/ns/ttml":style}' is expected.

Should I be using some options in the command line to get this fixed?
Fixing the Xml manually, seems to work fine.

**Comment by skynavga** [comment]
fixed in tag https://github.com/skynav/cap2tt/releases/tag/pre-alpha-2.1; adds new --default-language option (see also configuration file)

**Comment by shinjantiwary** [comment]
I do see the "jp" in the output XML, however this xml still doesn't seem to work with ttpe. I would probably open another ticket for it.

**Comment by skynavga** [comment]
probably because the default cap2tt configuration file [1] uses the new TTML2 tts:position attribute to position regions and we haven't added support for it yet in TTPE; we will add support for it by the end of March; in the mean time, you can use an alternate configuration file the uses the tts:origin property instead of the tts:position property; i will add an issue under TTPE to track this;

[1] https://github.com/skynav/cap2tt/blob/master/src/resources/com/skynav/cap2tt/app/cap2tt.xml

**Comment by shinjantiwary** [comment]
Yes I was able to modify the configuration file to the following to get around this problem:

I modified them as:

tts:writingMode="lrtb" tts:origin="256px 610px" tts:extent="768px 90px" tts:displayAlign="after" tts:textAlign="center" tts:fontFamily="Noto Sans" tts:fontSize="36px" tts:lineHeight="45px"

**Comment by shinjantiwary** [comment]
Have opened https://github.com/skynav/cap2tt/issues/8 for the same
